/**
 * Template form rules, TypeScript side.
 *
 * This is a line-for-line port of the rules in
 * backend/app/services/service_template_engine.py (visible_fields, missing_required,
 * strip_hidden). The browser uses it to hide fields and block submit; the server
 * re-checks everything. `templateRules.test.ts` replays vectors generated BY THE PYTHON
 * ENGINE so the two sides cannot drift apart silently.
 */

export interface TemplateOption { value: string; label: string; description?: string }
export interface TemplateSelector { key: string; label: string; required?: boolean; options: TemplateOption[] }
export interface VisibilityRule { field: string; in?: string[]; not_in?: string[] }
export interface TemplateField {
  key: string
  label: string
  type: 'text' | 'textarea' | 'phone' | 'email' | 'date' | 'select' | 'digits' | 'file' | 'nin_list'
  required?: boolean
  width?: 'full' | 'half' | 'third'
  section?: string
  help?: string
  options?: Array<string | TemplateOption>
  length?: number
  max_items?: number
  accept?: string
  sensitive?: boolean
  visible_when?: VisibilityRule[]
}
export interface TemplateSchema {
  schema_version?: number
  selectors: TemplateSelector[]
  fields: TemplateField[]
  fixed_service_type?: string
  quantity_from?: { field: string; when: Record<string, string> }
  uploaded_file_fields?: string[]
}

export type Answers = Record<string, unknown>

export function normalizeValue(v: unknown): string {
  return String(v).trim().toLowerCase().replace(/ /g, '_')
}

export function isBlank(v: unknown): boolean {
  if (v === null || v === undefined) return true
  if (typeof v === 'string') return v.trim() === ''
  if (Array.isArray(v)) return v.length === 0
  if (typeof v === 'object') return Object.keys(v as object).length === 0
  return false
}

function conditionOk(cond: VisibilityRule, answers: Answers): boolean {
  const got = answers[cond.field]
  const gotN = isBlank(got) ? null : normalizeValue(got)
  if (cond.in) return gotN !== null && cond.in.map(normalizeValue).includes(gotN)
  const notIn = (cond.not_in ?? []).map(normalizeValue)
  return gotN === null || !notIn.includes(gotN)
}

export function visibleFields(schema: TemplateSchema, answers: Answers): TemplateField[] {
  return schema.fields.filter((f) => (f.visible_when ?? []).every((c) => conditionOk(c, answers)))
}

export function missingRequired(schema: TemplateSchema, answers: Answers): string[] {
  const problems: string[] = []
  for (const sel of schema.selectors) {
    if ((sel.required ?? true) && isBlank(answers[sel.key])) problems.push(sel.label)
  }
  for (const f of visibleFields(schema, answers)) {
    const v = answers[f.key]
    if (f.required && isBlank(v)) {
      problems.push(f.label)
    } else if (f.type === 'digits' && !isBlank(v) && f.length) {
      const s = String(v)
      if (!(/^\d+$/.test(s) && s.length === f.length)) problems.push(`${f.label} (must be ${f.length} digits)`)
    }
  }
  return problems
}

export function stripHidden(schema: TemplateSchema, answers: Answers): Answers {
  const keep = new Set(visibleFields(schema, answers).map((f) => f.key))
  for (const s of schema.selectors) keep.add(s.key)
  const out: Answers = {}
  for (const [k, v] of Object.entries(answers)) {
    if (keep.has(k) && !isBlank(v)) out[k] = v
  }
  return out
}

/** Valid 11-digit NINs from a list or a block of text (junk lines are ignored). */
export function parseNinList(value: unknown): string[] {
  const items = typeof value === 'string' ? value.split(/\r?\n/) : Array.isArray(value) ? value : []
  const out: string[] = []
  for (const it of items) {
    const digits = String(it).replace(/\D/g, '')
    if (/^\d{11}$/.test(digits)) out.push(digits)
  }
  return out
}
